name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this if you deploy from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run:  bundle install
        # Add any commands you need to build your static site
        # For example, if you're using Jekyll:
        bundle install

    - name: Build the site
      run:  bundle exec jekyll build

        # Replace with the appropriate build command
        # Example for Jekyll:
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site # Adjust to the folder where your static files are generated
